GUISevenCodeOnlineStore/Areas/Customer/Controllers/CartController.cs
using BLLSevenCodeOnlineStore.BaseRepository;
using BLLSevenCodeOnlineStore.ModelRepositories.Admin;
using DALSevenCodeOnlineStore;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace GUISevenCodeOnlineStore.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class CartController : Controller
    {
      
        public IProductRepository _iProductRepository;
        private readonly SevenCodeOnlineStoreContext _context;
        public CartController(SevenCodeOnlineStoreContext context)
        {
       
            _iProductRepository = new ProductRepository();
            _context = context;
        }
 
        public IActionResult Index()
        {
            List<Products> products = new List<Products>();
            products = HttpContext.Session.Get<List<Products>>("products");
            return View(products);
        }

        [HttpGet]
        public IActionResult addtoCart(int? id)
        {
            List<Products> products = new List<Products>();
            if (id == null)
            {
                return NotFound();
            }
            Products product =(Products) _iProductRepository.GetById(id);
            products = HttpContext.Session.Get<List<Products>>("products") ;
            if (products == null)
            {
                products = new List<Products>();
            }
            products.Add(product);
            HttpContext.Session.Set("products", products);
            if (products == null)
            {
                products = new List<Products>();
            }
            return RedirectToAction("Index", products);
        }


        [HttpGet]
        public IActionResult Details(int? id)
        {
            Products product = (Products)_iProductRepository.GetById(id);
            return View(product);
        }
        [HttpGet]
        public IActionResult delete(int ?id)
        {
            List<Products> products = HttpContext.Session.Get<List<Products>>("products");
            if (products != null)
            {
                var product = products.FirstOrDefault(c => c.Id == id);
                if (product != null)
                {
                    products.Remove(product);
                    HttpContext.Session.Set("products", products);
                }
            }
            return RedirectToAction("Index");
        }



    }
}

GUISevenCodeOnlineStore/Areas/Customer/Controllers/CheckoutController.cs
using BLLSevenCodeOnlineStore.ModelRepositories.Admin;
using DALSevenCodeOnlineStore;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace GUISevenCodeOnlineStore.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class CheckoutController : Controller
    {
        public IProductRepository _iProductRepository;
        private readonly SevenCodeOnlineStoreContext _context;
        public CheckoutController(SevenCodeOnlineStoreContext context)
        {

            _iProductRepository = new ProductRepository();
            _context = context;
        }


        public IActionResult Index()
        {
            List<Products> products = new List<Products>();
            products = HttpContext.Session.Get<List<Products>>("products");
            //if(products == null || products.Count == 0)
            //{
            //    return View(products);
            //}
            return View(products);
           // return View();
        }
        //============ show checkout ==========
        public IActionResult ShowDetailCheckout(int?id)
        {
            Products product = (Products)_iProductRepository.GetById(id);
            return View(product);
        }

    }
}

GUISevenCodeOnlineStore/Areas/Customer/Views/Cart/Details.cshtml
@model DALSevenCodeOnlineStore.Products
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}
<link href="~/dist/css/CustomerCss/CheckoutCss.css" rel="stylesheet" />

<div class="container stylequery containdetails" style=" height: 780px;">
    <div class="row" style="margin-top:100px;">
        <div class="col-lg-6 col-sm-12 imagestylecolsmall">
            <img style="" src="~/Zimage/Products/@Model.Image" class="img-fluid imagestyle" alt="empty cart" />
        </div>
        <div style="background-color:white;padding:19px;" class="col-lg-6 col-sm-12">
            <h3 class="mt-3">
             Name :  @Model.Name
            </h3>
            <h3 id="price" class="mt-3">
                @Model.Price
            </h3>
            <h3 class="mt-3">
                Type : 
            </h3>
            <h3>
                Quantity : 
            </h3>
            <div class="mt-3">
                <input class="increase" onclick="increaseitem()" type="button" value="<" />
                <input id="quantity" type="number" min="1" class="inputfield" />
                <input class="decrease" onclick="decrement()" type="button" value=">" />
               @* <p id="total"></p>*@
            </div>
           
            <div class="row mt-3">
                <div class="col-6">
                @*    <a asp-area="Customer" asp-controller="Cart" asp-action="addtoCart" asp-route-id="Id" class="ml-1 btn pull-right btn-outline-info">
                        <i class="fas fa-shopping-cart"></i>
                    </a>*@
                    <a asp-area="Customer" asp-controller="Cart" asp-action="addtoCart" asp-route-id="@Model.Id" class="btn btnindetails">
                        ADD TO CART
                    </a>
                </div>
                <div class="col-6">
                    <a href="@Url.Action("Index", "Checkout", new { Area = "Customer" })" class="btn btnindetails">
                        BUY NOW
                    </a>
                </div>
            </div>

            <h3 class="mt-4">Description : </h3>
            @Model.Description
        </div>
        
    </div>

</div>
<script>
    var data = 1;
    document.getElementById("quantity").value = data;
    function increaseitem(){
        var pri=document.getElementById("price").innerHTML;
        //var totalpri = document.getElementById("total");
        //totalpri=pri*data;
        console.log("price => "+pri)
            data = data + 1;
        document.getElementById("quantity").value = data;
        }
    function decrement() {
        if(data>1){
            data = data - 1;
            document.getElementById("quantity").value = data;
        }
       
    }
</script>

GUISevenCodeOnlineStore/Areas/Customer/Views/Cart/Index.cshtml
@model IEnumerable<DALSevenCodeOnlineStore.Products>
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}

<link href="~/dist/css/CustomerCss/CheckoutCss.css" rel="stylesheet" />
@*<div class="row" style="margin-top:100px;padding:13px;background-color:white;">
    <div class="col-sm-6">
        <h1 class="pdirectionArabic m-0">CART</h1>
    </div>
    <div class="col-sm-6" style="float:right;">
        <ol class="breadcrumb pdirectionArabic">
            <li class="breadcrumb-item">HOME</li>
            <li class="breadcrumb-item pdirectionArabic ">CART</li>
        </ol>
    </div>
</div>*@

<div class="container containertable containcart">
    @*============ Empty Cart ==========*@
    @if (Model == null || Model.Count() == 0)
    {
        <div style="height: 690px;">
            <div class="row" style="margin-top:190px;">
    <div class="col-sm-12">
    <div class="col-sm-12 empty-cart-cls text-center">
    <img src="~/dist/img/icon-empty-cart.png" class="img-fluid" alt="empty cart">
    <h3 class="mt-3">
    <strong>Your Cart is Empty</strong>
    </h3>
    <h4 class="mb-3">Add something to make me happy :)</h4>
    <div class="col-12">
    <a href="@Url.Action("Index", "Home", new { Area = "" })" class="btncontinueshop">
    continue shopping
    </a>
    </div>
    </div>
    </div>
            </div></div>
    }
    @*========================= list of product in  cart ================*@
    else{

    <div>
    <table class="bg-gradient-white text-center table table-hover" style="margin-top:130px;">
        <thead>
            <tr>
                <th>IMAGE</th>
                <th>NAME</th>
                <th>PRICE</th>
                <th>QUANTITY</th>
                <th>ACTION</th>
                <th>COLOR</th>
                <th>TOTAL FOR ITEMS</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
                {
                    <tr>
                            <td><img src="~/Zimage/Products/@item.Image" style="height: 120px;" /></td>
                        <td> @item.Name </td>
                        <td> @item.Price </td>
                        <td>
                            <div class=" ">
                                <input class="increase" onclick="increaseitem()" type="button" value="<" />
                                <input value="1" id="quantity" type="number" min="1" class="inputfield" />
                                <input class="decrease" onclick="decrement()" type="button" value=">" />
                            </div>
                        </td>
                            <td>
                                <a asp-area="Customer" asp-controller="Cart" asp-action="delete" asp-route-id="@item.Id" class=" ">
                                    <i style="color: #ff4c3b !important;" class="fa fa-trash" aria-hidden="true"></i>
                                </a>
                            </td>
                            <td>
                                @item.ProductColor
                            </td>
                            <td id="totalprice">@item.Price<td>
                    </tr>
                }
               
        </tbody>
    </table>

            <span style="font-size: 24px;" class="float-right mt-4">Total Price: <strong id="forallsum" > @Model.Sum(i=>i.Price) </strong> </span>
        <br />
        <br />
        <div class="row mt-3 mb-4">
            <div class="col-6">
                <a href="@Url.Action("Index", "Home", new { Area = "" })" class="btn btnindetailscontinueshop">
                    continue shopping
                </a>
            </div>
            <div class="col-6">
                <a href="@Url.Action("Index", "Checkout", new { Area = "Customer" })" class="btn btnindetailscartcheck">
                    check out
                </a>
            </div>
        </div>
    </div>
    }

</div>


<script>
    var data = 1;
    var da = 1;
    document.getElementById("quantity").value = data;
    function increaseitem() {
        if (data < 5) {
        data = data + 1;
        document.getElementById("quantity").value = data;
        total();
        }
    }
    function decrement() {
        if (data > 1) {
            data = data - 1;
            document.getElementById("quantity").value = data;
            total();
        }
    }

    ///==================== sum of total price =========
    function total(){
      var qua=  document.getElementById("quantity").value = data;
        var pri = document.getElementById("totalprice").innerHTML;
        da = qua * pri;
        document.getElementById("totalprice").innerHTML =da ;


        @*document.getElementById("forallsum").innerHTML += da;*@
        console.log("price => " + pri+"total===>"+ qua*pri);
    }
</script>